New Func: /start_game
IgorL123/mafia_api pull request #6
Opened 2023-08-23 13:19 UTC by ada-dmitry

2023-08-23 13:55 UTC, IgorL123 requested changes

2023-08-23 13:55 UTC, IgorL123 commented on __pycache__/db.cpython-311.pyc
убери это

2023-08-23 13:55 UTC, IgorL123 commented on api_functions.py
оставь комент в коде как твое распределение работает

2023-08-23 13:55 UTC, IgorL123 commented on app.py
db.close() разве сработает ?

2023-08-24 09:25 UTC, ada-dmitry commented on __pycache__/db.cpython-311.pyc
убрал, вроде, ж

2023-08-24 09:35 UTC, ada-dmitry commented on api_functions.py
оставил

2023-08-24 09:35 UTC, ada-dmitry commented on app.py
теперь сработает)

2023-08-24 18:33 UTC, merged